name: NIX CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Learn4Haskell
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: learn4haskell
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-shell --run "cabal v2-build --enable-tests --enable-benchmarks"

